repository:
    # See https://developer.github.com/v3/repos/#edit for all available settings.

    # The name of the repository. Changing this will rename the repository
    #name: repo-name

    # A short description of the repository that will show up on GitHub
    #description: description of repo

    # A URL with more information about the repository
    #homepage: https://example.github.io/

    # A comma-separated list of topics to set on the repository
    #topics: project, template, project-template

    # Either `true` to make the repository private, or `false` to make it public.
    private: false

    # Either `true` to enable issues for this repository, `false` to disable them.
    has_issues: true

    # Either `true` to enable the wiki for this repository, `false` to disable it.
    has_wiki: false

    # Either `true` to enable downloads for this repository, `false` to disable them.
    has_downloads: false

    # Updates the default branch for this repository.
    default_branch: master

    # Either `true` to allow squash-merging pull requests, or `false` to prevent
    # squash-merging.
    allow_squash_merge: true

    # Either `true` to allow merging pull requests with a merge commit, or `false`
    # to prevent merging pull requests with merge commits.
    allow_merge_commit: true

    # Either `true` to allow rebase-merging pull requests, or `false` to prevent
    # rebase-merging.
    allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:

    - name: 'BUG üêû'
      color: ff0000
      description: Something isn't working

    - name: 'DISCUSSION üí¨'
      color: cfd3d7
      description: Discussion Thread

    - name: 'DOCS üìò'
      color: 0075ca
      description: Improvements or additions to documentation

    - name: 'EPIC üìå'
      color: 7057ff
      description: Work unit containing sub-tasks

    - name: 'FEATURE üö©'
      color: 00ff00
      description: New feature or request

    - name: 'QUESTION ‚ùì'
      color: d876e3
      description: Support Question

    - name: 'REQUEST üöß'
      color: FBCA04
      description: Feature request or suggestion

    - name: 'RESPONSE REQUIRED üö®'
      color: B60205
      description: Response required by admin

    - name: 'good first issue'
      color: 0052CC
      description: Good first issue for new contributor

    - name: 'help wanted'
      color: 0E8A16
      description: Extra attention is required

    - name: 'üí§ STALE'
      color: C2E0C6
      description:

    - name: 'Priority: Critical ++'
      color: B60205
      description:

    - name: 'Priority: High +'
      color: D93F0B
      description:

    - name: 'Priority: Medium ='
      color: FBCA04
      description:

    - name: 'Priority: Low -'
      color: 0E8A16
      description:

    - name: 'Priority: None --'
      color: c5def5
      description:

    - name: 'Status: Triage'
      color: 5319E7
      description: (TRIAGE)

    - name: 'Status: Confirmed'
      color: 0052CC
      description: (TODO)

    - name: 'Status: ToDo'
      color: 0052CC
      description: (TODO)

    - name: 'Status: Blocked'
      color: 000000
      description: (BLOCKED)

    - name: 'Status: Returned'
      color: D93F0B
      description: (REVIEWER RETURNED)

    - name: 'Status: In Progress'
      color: FBCA04
      description: (IN PROGRESS)

    - name: 'Status: Blocking'
      color: B60205
      description: (BLOCKING)

    - name: 'Status: For Review'
      color: 006B75
      description: (FOR REVIEW)

    - name: 'Status: Under Review'
      color: 0E8A16
      description: (UNDER REVIEW)

    - name: 'Status: To Merge'
      color: F9D0C4
      description: (TO MERGE)

    - name: "Status: Can't Replicate"
      color: D4C5F9
      description: (CLOSED)

    - name: 'Status: Duplicate'
      color: D4C5F9
      description: (CLOSED)

    - name: "Status: Won't Fix"
      color: D4C5F9
      description: (CLOSED)

    - name: 'Status: DONE'
      color: 0E8A16
      description: (DONE)

# Collaborators: give specific users access to this repository.
#collaborators:
#    - username: bkeepers
          # Note: Only valid on organization-owned repositories.
          # The permission to grant the collaborator. Can be one of:
          # * `pull` - can pull, but not push to or administer this repository.
          # * `push` - can pull and push, but not administer this repository.
          # * `admin` - can pull, push and administer this repository.
          # permission: push
